# Generated by Django 4.2.3 on 2023-07-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_verified_dairy',
            field=models.BooleanField(default=False),
        ),
    ]
