# Generated by Django 4.2.3 on 2023-08-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0002_user_has_verified_dairy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='has_verified_dairy',
            field=models.BooleanField(default=False, verbose_name='has verified dairy'),
        ),
    ]
