# Generated by Django 4.2.3 on 2023-09-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0003_alter_user_has_verified_dairy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.BigIntegerField(unique=True, verbose_name='phone number'),
        ),
    ]
