# Generated by Django 4.2.3 on 2023-09-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=40, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_verified_dairy',
            field=models.BooleanField(default=False, verbose_name='Has verified dairy'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='Email verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=40, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.BigIntegerField(unique=True, verbose_name='Phone number'),
        ),
    ]
