# Generated by Django 4.2.3 on 2023-07-26 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dairy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='name')),
                ('location', models.CharField(max_length=200, verbose_name='location')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('members', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='dairy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dairies', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'dairy',
                'verbose_name_plural': 'dairies',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=10, unique=True)),
                ('age', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FatRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fat_rate', models.FloatField(max_length=5, verbose_name='fat rate')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('dairy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.dairy', verbose_name='dairy')),
            ],
        ),
        migrations.CreateModel(
            name='MilkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('day', 'day'), ('night', 'night')], max_length=10)),
                ('milk_weight', models.FloatField()),
                ('milk_fat', models.FloatField(max_length=5)),
                ('date', models.DateField(verbose_name='date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('dairy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.dairy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('dairy', 'user', 'shift', 'date')},
            },
        ),
    ]
