# Generated by Django 4.2.3 on 2023-07-28 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0002_alter_milkrecord_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatrate',
            name='dairy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.dairy', verbose_name='dairy'),
        ),
    ]
