# Generated by Django 4.2.3 on 2023-08-02 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dairyapp', '0003_alter_fatrate_dairy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AlterField(
            model_name='milkrecord',
            name='dairy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.dairy', verbose_name='dairy'),
        ),
        migrations.AlterField(
            model_name='milkrecord',
            name='milk_fat',
            field=models.FloatField(max_length=5, verbose_name='milk fat'),
        ),
        migrations.AlterField(
            model_name='milkrecord',
            name='milk_weight',
            field=models.FloatField(verbose_name='milk weight'),
        ),
        migrations.AlterField(
            model_name='milkrecord',
            name='shift',
            field=models.CharField(choices=[('morning', 'morning'), ('night', 'night')], max_length=10, verbose_name='shift'),
        ),
        migrations.AlterField(
            model_name='milkrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
