# Generated by Django 4.2.3 on 2023-09-11 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0005_fatrate_bonuus_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fatrate',
            old_name='bonuus_amount',
            new_name='bonous_amount',
        ),
    ]
