# Generated by Django 4.2.3 on 2023-09-18 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dairyapp', '0006_rename_bonuus_amount_fatrate_bonous_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkReportEmailHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('morning', 'morning'), ('night', 'night')], max_length=10, verbose_name='shift')),
                ('fat_rate', models.FloatField(max_length=5, verbose_name='fat rate')),
                ('bonous_amount', models.PositiveSmallIntegerField(default=0, verbose_name='Bonous amount')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('dairy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.dairy', verbose_name='dairy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
