# Generated by Django 4.2.3 on 2023-09-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0007_milkreportemailhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkreportemailhistory',
            name='avg_fat',
            field=models.FloatField(default=0, verbose_name='Avg fat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='milkreportemailhistory',
            name='milk_weight',
            field=models.FloatField(default=0, verbose_name='milk weight'),
            preserve_default=False,
        ),
    ]
