# Generated by Django 4.2.3 on 2023-09-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0008_milkreportemailhistory_avg_fat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkreportemailhistory',
            name='total_amoubt',
            field=models.FloatField(default=0, verbose_name='Total amount'),
            preserve_default=False,
        ),
    ]
