# Generated by Django 4.2.3 on 2023-09-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0009_milkreportemailhistory_total_amoubt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milkreportemailhistory',
            old_name='total_amoubt',
            new_name='total_amount',
        ),
    ]
