# Generated by Django 4.2.3 on 2023-09-19 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0010_rename_total_amoubt_milkreportemailhistory_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatrate',
            name='dairy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.dairy', verbose_name='dairy'),
        ),
    ]
