# Generated by Django 4.2.3 on 2023-10-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0012_alter_dairy_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkrecord',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning'), ('night', 'Night')], max_length=10, verbose_name='shift'),
        ),
    ]
