# Generated by Django 4.2.3 on 2023-10-05 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0013_alter_milkrecord_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatrate',
            name='created_at',
            field=models.DateField(default=datetime.date(2023, 10, 5), verbose_name='created at'),
        ),
    ]
