# Generated by Django 4.2.3 on 2023-10-05 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0014_alter_fatrate_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatrate',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 10, 5, 15, 35, 7, 838186, tzinfo=datetime.timezone.utc), verbose_name='created at'),
        ),
    ]
