# Generated by Django 4.2.3 on 2023-10-16 03:09

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0019_alter_fatrate_created_at_alter_fatrate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dairy',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fatrate',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 3, 8, 59, 356451, tzinfo=datetime.timezone.utc), verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='milkrecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='milkreportemailhistory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
