# Generated by Django 4.2.3 on 2023-10-16 03:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0020_alter_dairy_id_alter_fatrate_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatrate',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 3, 13, 45, 406835, tzinfo=datetime.timezone.utc), verbose_name='created at'),
        ),
    ]
