# Generated by Django 4.2.3 on 2023-10-23 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0027_alter_fatrate_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatrate',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 23, 13, 46, 4, 777503, tzinfo=datetime.timezone.utc), verbose_name='created at'),
        ),
    ]
